#!/bin/bash
# requires curl

# Get stats like disk free space (%) and RAM free (MB)

# Cut column whitespace delimited
# $1 is data
# $2 is column(s) to keep
fields_whitespace_delim() { 
  echo "$1" | tr -s ' ' | cut -d ' ' -f $2
}

drop_first_line() {
  echo "$1" | sed -e '1d'
}

remove_non_numeric() {
  echo "$1" | sed 's/[^0-9]*//g'
}

disk_free() {
  for device in "${diskdevice[@]}"
  do
    dfline=`df -h | grep $device`
    if [[ "$dfline" != "" ]]; then
      df1=$(fields_whitespace_delim "$dfline" 5)
      diskused=$(remove_non_numeric "$df1")
      declare -i result
      result=100-diskused
      echo "$result"
      return
    fi
  done
}

ram_free() {
  freeline=`free -m | grep buffers/cache`
  declare -i free
  free=$(fields_whitespace_delim "$freeline" 4)
  echo "$free"
}

app_running() {
  if [ $(curl -s "$checkurl" | grep "$okhtml" > /dev/null) ]; then
    echo "ok"
  else
    echo "fail"
  fi
}

collectall() {
  disk_free $diskdevice
  ram_free
  app_running
}

collectall

